# define input from beats events
- pipeline.id: input-beats
  path.config: "pipeline/input-beats.conf"
# define outputs for user, status and audit events
- pipeline.id: user
  path.config: "pipeline/dynamic-user.conf"
- pipeline.id: display-state
  path.config: "pipeline/dynamic-display-state.conf"
- pipeline.id: communicator-state
  path.config: "pipeline/dynamic-communicator-state.conf"
- pipeline.id: service-status
  path.config: "pipeline/dynamic-service-status.conf"
- pipeline.id: audit
  path.config: "pipeline/dynamic-audit.conf"
- pipeline.id: fallback
  path.config: "pipeline/fallback.conf"
# define input for user events files
- pipeline.id: input-file-user
  path.config: "pipeline/input-file-user.conf"
- pipeline.id: file-user
  path.config: "pipeline/dynamic-file-user.conf"
- pipeline.id: file-display-state
  path.config: "pipeline/dynamic-file-display-state.conf"
- pipeline.id: file-communicator-state
  path.config: "pipeline/dynamic-file-communicator-state.conf"
- pipeline.id: input-file-service-status
  path.config: "pipeline/input-file-service-status.conf"
- pipeline.id: file-service-status
  path.config: "pipeline/dynamic-file-service-status.conf"
- pipeline.id: input-file-audit
  path.config: "pipeline/input-file-audit.conf"
- pipeline.id: file-audit
  path.config: "pipeline/dynamic-file-audit.conf"





