- pipeline.id: user
  path.config: "/usr/share/logstash/pipeline/dynamic-user.conf"
# - pipeline.id: audit
#   path.config: "/usr/share/logstash/pipeline/dynamic-audit.conf"
- pipeline.id: status
  path.config: "/usr/share/logstash/pipeline/dynamic-status.conf"
