#
# Filebeat is configured to look for the other container log files and send
# them to elasticsearch
#
# Currently, only logstash is being sent for analysis
#
# Ingest pipelines need to be loaded before logstash starts:
#  This done in the start-up script: filebeat setup --pipelines --modules logstash

filebeat.autodiscover:
  providers:
  - type: docker
    hints.enabled: false
    hints.default_config.enabled: false
    templates:
      - condition:
          contains:
            docker.container.image: logstash
        config:
          - type: container
            paths:
              - "/var/lib/docker/containers/${data.docker.container.id}/*.log"

processors:
# - add_cloud_metadata: ~
- add_docker_metadata: ~

output.elasticsearch:
  hosts: '${ELASTICSEARCH_HOSTS:elasticsearch:9200}'
  username: '${ELASTICSEARCH_USERNAME:elastic}'
  password: '${ELASTICSEARCH_PASSWORD:elastic}'

